public enum State {
  SVR_STATE_PREPARING,
  SVR_STATE_WAITING_FOR_COMMIT_ACK,
  SVR_STATE_WAITING_FOR_ABORT_ACK,
  SVR_STATE_DONE,
  USER_STATE_CHECKING,
  USER_STATE_YES,
  USER_STATE_COMMITING,
  USER_STATE_ABORTING,
  USER_STATE_COMMIT_ACKED,
  USER_STATE_ABORT_ACKED
}
